spring:
  application:
    name: spring-shooter

game:
  settings:
    fps: 60

debug: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level){blue} %clr(%logger{36}){green} - %msg%n"
